# Generated by Django 4.2.7 on 2023-11-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
