# Generated by Django 4.2.7 on 2023-11-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Pastor', 'Pastor'), ('Teacher', 'Teacher'), ('Parent', 'Parent')], default='Parent', max_length=20),
        ),
    ]
