# Generated by Django 4.2.7 on 2023-11-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=10, unique=True)),
                ('seats', models.PositiveIntegerField(choices=[(14, 14), (52, 52), (62, 62)])),
                ('zone', models.CharField(choices=[('Ngong,Kiserian,Rongai', 'Ngong,Kiserian,Rongai'), ('Karen, Bulbul, Nairobi', 'Karen, Bulbul, Nairobi')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
