# Generated by Django 4.2.7 on 2023-11-27 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bus_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='zone',
            field=models.CharField(choices=[('Ngong, Kiserian, Rongai', 'Ngong, Kiserian, Rongai'), ('Karen, Bulbul, Nairobi', 'Karen, Bulbul, Nairobi')], max_length=50),
        ),
    ]
