# Generated by Django 4.2.7 on 2023-11-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_teacher_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='password',
        ),
    ]
