# Generated by Django 4.2.7 on 2023-11-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_student_last_login_remove_student_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('8', '7'), ('8', '8')], max_length=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parent',
            name='role',
            field=models.CharField(choices=[('Pastor', 'Pastor'), ('Teacher', 'Teacher'), ('Parent', 'Parent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('Pastor', 'Pastor'), ('Teacher', 'Teacher'), ('Parent', 'Parent')], max_length=20),
        ),
    ]
