# Generated by Django 4.2.7 on 2023-11-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_classroom_grade_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.SmallIntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
